CREATE DATABASE DB_GENERATION_GAME_ONLINE;
USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSE(
ID BIGINT AUTO_INCREMENT,
POSICAO VARCHAR(100) NOT NULL,
PRIMARY KEY(ID)
);
ALTER TABLE TB_CLASSE ADD (HABILIDADE VARCHAR (100) NOT NULL);

CREATE TABLE TB_PERSONAGEM(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
NIVEL INT NOT NULL,
PODER_ATAQUE INT NOT NULL,
PODER_DEFESA INT NOT NULL,
CLASSE_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (CLASSE_ID) REFERENCES TB_CLASSE(ID)
);

INSERT INTO TB_CLASSE(POSICAO, HABILIDADE)
values("ARQUEIRO","FOGO"),
("MAGO", "GELO"),
("LUTADOR", "ELETRICO"),
("ESPADA","AGUA"),
("VOADIR","VENTO");

INSERT INTO TB_PERSONAGEM(NOME, NIVEL, PODER_ATAQUE, PODER_DEFESA,CLASSE_ID)
VALUES ("SONA",50,4000,2600,1),
("RAGNAR",30,2000,5000,2),
("AKALI",40,1000,2600,1),
("TEEMO",20,3000,2600,3),
("SAPHIRA",10,500,3600,5),
("VIKTOR",8,600,4600,4),
("JOHN",70,1800,1600,3),
("KAISA",25,1500,2600,4);

SELECT * FROM TB_CLASSE;
SELECT * FROM TB_PERSONAGEM;

SELECT * FROM TB_PERSONAGEM WHERE PODER_ATAQUE > 2000;

SELECT * FROM TB_PERSONAGEM WHERE PODER_DEFESA > 1000 AND PODER_DEFESA <2000;

SELECT * FROM TB_PERSONAGEM WHERE NOME LIKE "%C%"; 

SELECT * FROM TB_PERSONAGEM INNER JOIN tb_classe ON
tb_personagem.CLASSE_ID = tb_classe.ID;

SELECT * FROM TB_PERSONAGEM INNER JOIN tb_classe ON
tb_personagem.CLASSE_ID = tb_classe.ID WHERE POSICAO = "ARQUEIRO";