CREATE DATABASE DB_FARMACIA_BEM_ESTAR;
USE DB_FARMACIA_BEM_ESTAR;

CREATE TABLE TB_CATEGORIAS(
ID INT AUTO_INCREMENT,
TIPO VARCHAR(100) NOT NULL,
MARCA VARCHAR (100) NOT NULL, 
PRIMARY KEY (ID));

CREATE TABLE TB_PRODUTO(
ID INT AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
PRECO DECIMAL(6,2) NOT NULL,
QTD INT NOT NULL,
DESCRICAO VARCHAR (100) NOT NULL,
TIPO_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (TIPO_ID) REFERENCES TB_CATEGORIAS(ID));

INSERT INTO TB_CATEGORIAS(TIPO, MARCA)
VALUES("REMEDIO", "ACHÉ"),
("REMEDIO", "EMS"),
("CURATIVOS", "NEEDS"),
("COSMETICOS", "SEDA"),
("FRALDAS", "HUGGIES");

INSERT INTO TB_PRODUTO(NOME, PRECO, QTD, DESCRICAO, TIPO_ID)
VALUES ("DIOVAN", 129.00, 10, "REMEDIO DE PRESSAO", 1),
("RESFENOL", 30.00, 10, "REMEDIO DE GRIPE", 2),
("SHAMPOO", 85.00, 10, "SHAMPOO GARNIER FRUCTIS", 4),
("BAND AID", 20.00, 10, "CURATIVO", 1),
("SALOMPAS", 8.00, 10, "ADESIVO PARA ALIVIAR DOR", 3),
("LOREAL", 99.00, 10, "COLORACAO PARA CABELO",4),
("PAMPERS", 56.00, 10, "FRALDAS MEDIOS", 5),
("HUGGIES", 64.00, 10, "FRALDAS PEQUENAS", 5);

SELECT * FROM DB_FARMACIA_BEM_ESTAR.TB_CATEGORIAS;

SELECT * FROM DB_FARMACIA_BEM_ESTAR.TB_PRODUTO;

SELECT NOME, PRECO FROM TB_PRODUTO WHERE PRECO > 50.00;

SELECT NOME, PRECO FROM TB_PRODUTO WHERE PRECO > 5.00 AND PRECO < 60.00;

SELECT NOME, PRECO, DESCRICAO FROM TB_PRODUTO WHERE NOME LIKE "%C%";

SELECT NOME, PRECO, DESCRICAO, TIPO_ID FROM TB_PRODUTO INNER JOIN TB_CATEGORIAS ON
TB_PRODUTO.TIPO_ID = TB_CATEGORIAS.ID;

SELECT NOME, PRECO, DESCRICAO, TIPO_ID, TIPO FROM TB_PRODUTO INNER JOIN TB_CATEGORIAS ON
TB_PRODUTO.TIPO_ID = TB_CATEGORIAS.ID WHERE TIPO = "COSMETICOS";
