CREATE DATABASE DB_PIZZARIA_LEGAL;
USE DB_PIZZARIA_LEGAL;
	
CREATE TABLE TB_CATEGORIA(
ID BIGINT AUTO_INCREMENT NOT NULL,
TIPO VARCHAR (100) NOT NULL,
TAMANHO CHAR (50) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_PIZZA(
ID BIGINT AUTO_INCREMENT NOT NULL,
NOME VARCHAR (100) NOT NULL,
PRECO DECIMAL (5,2) NOT NULL,
QTPIZZA INT (10)NOT NULL,
INGREDIENTE VARCHAR(100) NOT NULL,
TIPO_ID BIGINT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (TIPO_ID) REFERENCES TB_CATEGORIA(ID)
);

INSERT INTO TB_CATEGORIA(TIPO, TAMANHO)
VALUES("SALGADO","PEQUENO"),
("SALGADO", "MEDIO"),
("SALGADO", "GRANDE"),
("DOCE", "PEQUENO"),
("DOCE", "MEDIO");

INSERT INTO TB_PIZZA(NOME, PRECO, QTPIZZA, INGREDIENTE, TIPO_ID)
VALUES("CALABRESA", 49.99, 10, "CALABRESA", 1),
("MUSSARELA", 100.99, 10, "QUEIJO", 2),
("BRASILEIRA", 41.99, 10, "CEBOLA E QUEIJO", 3),
("NUTELLA", 20.99, 10, "NUTELLA", 4),
("BRIGADEIRO", 53.99, 10, "CHOCOLATE", 5),
("PERUANA", 100.99, 10, "PERU, QUEIJO", 1),
("BAHIANA", 112.99, 10, "CALABRESA, CEBOLA", 2),
("MILHO VERDE", 69.99, 10, "MILHO , BACON", 3);

SELECT * FROM TB_CATEGORIA;
SELECT * FROM TB_PIZZA;

SELECT * FROM TB_PIZZA WHERE PRECO > 45.00;

SELECT * FROM TB_PIZZA WHERE PRECO > 50.00 AND PRECO < 100.00;

SELECT * FROM TB_PIZZA WHERE NOME LIKE "%M%";

SELECT * FROM TB_CATEGORIA INNER JOIN TB_PIZZA ON
TB_CATEGORIA.ID = TB_PIZZA.TIPO_ID;

SELECT * FROM TB_CATEGORIA INNER JOIN TB_PIZZA ON
TB_CATEGORIA.ID = TB_PIZZA.TIPO_ID WHERE TIPO = "DOCE";
