CREATE DATABASE DB_ALUNOS_ESCOLA;

USE DB_ALUNOS_ESCOLA;

CREATE TABLE TB_ALUNOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
CLASSE CHAR(255),
PROFESSOR CHAR(255),
RA INT,
COR CHAR(255),
NOTAFINAL INT,
PRIMARY KEY(ID)
);

INSERT INTO TB_ALUNOS (NOME, CLASSE, PROFESSOR, RA, COR, NOTAFINAL)
VALUE ("Marcelo","7B","Cleide",29312,"Pardo",8);
INSERT INTO TB_ALUNOS (NOME, CLASSE, PROFESSOR, RA, COR, NOTAFINAL)
VALUE ("Fernanda","3A","Geise",32403,"Branca",7);
INSERT INTO TB_ALUNOS (NOME, CLASSE, PROFESSOR, RA, COR, NOTAFINAL)
VALUE ("Claudio","8B","Joana",30934,"Preto",9);
INSERT INTO TB_ALUNOS (NOME, CLASSE, PROFESSOR, RA, COR, NOTAFINAL)
VALUE ("Vinicius","2C","Valdeci",31257,"Branco",6);
INSERT INTO TB_ALUNOS (NOME, CLASSE, PROFESSOR, RA, COR, NOTAFINAL)
VALUE ("Larissa","7C","Norma",29540,"Preta",5);
INSERT INTO TB_ALUNOS (NOME, CLASSE, PROFESSOR, RA, COR, NOTAFINAL)
VALUE ("Diego","2A","Lucia",31239,"Pardo",6);
INSERT INTO TB_ALUNOS (NOME, CLASSE, PROFESSOR, RA, COR, NOTAFINAL)
VALUE ("Talita","3A","Geise",32596,"Branca",4);
INSERT INTO TB_ALUNOS (NOME, CLASSE, PROFESSOR, RA, COR, NOTAFINAL)
VALUE ("Suellen","6B","André",27967,"Preta",9);

SELECT * FROM TB_ALUNOS WHERE NOTAFINAL >= 7;

SELECT * FROM TB_ALUNOS WHERE NOTAFINAL < 7;

SET SQL_SAFE_UPDATES = 0;  

UPDATE TB_ALUNOS SET NOTAFINAL = 7 WHERE ID = 7;

SELECT * FROM TB_ALUNOS;