CREATE DATABASE DB_PRODUTOS_ECOMMERCE;

USE DB_PRODUTOS_ECOMMERCE;

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
CATEGORIA CHAR(255),
VALOR INT,
TAMANHO CHAR(255),
QUANTIDADE INT,
COR CHAR(255),
PRIMARY KEY(ID)
);

INSERT INTO TB_PRODUTOS (CATEGORIA, VALOR, TAMANHO, QUANTIDADE, COR)
VALUE ("Mouse",149.90,"Pequeno",1,"Azul");
INSERT INTO TB_PRODUTOS (CATEGORIA, VALOR, TAMANHO, QUANTIDADE, COR)
VALUE ("Teclado",239.90,"Medio",1,"Branco Fosco");
INSERT INTO TB_PRODUTOS (CATEGORIA, VALOR, TAMANHO, QUANTIDADE, COR)
VALUE ("Monitor",1239.90,"Grande",1,"Cinza");
INSERT INTO TB_PRODUTOS (CATEGORIA, VALOR, TAMANHO, QUANTIDADE, COR)
VALUE ("Gabinete",1449.00,"Grande",1,"Colorido");
INSERT INTO TB_PRODUTOS (CATEGORIA, VALOR, TAMANHO, QUANTIDADE, COR)
VALUE ("Mousepad",32.90,"Pequeno",2,"Estampado");
INSERT INTO TB_PRODUTOS (CATEGORIA, VALOR, TAMANHO, QUANTIDADE, COR)
VALUE ("Headset",699.90,"Medio",2,"Cinza espacial");
INSERT INTO TB_PRODUTOS (CATEGORIA, VALOR, TAMANHO, QUANTIDADE, COR)
VALUE ("Carregador",199.00,"Pequeno",3,"Branco");
INSERT INTO TB_PRODUTOS (CATEGORIA, VALOR, TAMANHO, QUANTIDADE, COR)
VALUE ("Adaptador HDMI",26.90,"Pequeno",2,"Preto");

SELECT * FROM TB_PRODUTOS WHERE VALOR > 500;

SELECT * FROM TB_PRODUTOS WHERE VALOR < 500;

SET SQL_SAFE_UPDATES = 0;  

UPDATE TB_PRODUTOS SET QUANTIDADE = 2 WHERE ID = 2;

SELECT * FROM TB_PRODUTOS;