CREATE DATABASE DB_RH_EMPRESA;

USE DB_RH_EMPRESA;

CREATE TABLE TB_COLABS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
SALARIO FLOAT,
FUNCAO CHAR(255),
SETOR CHAR(255),
SUPERIOR CHAR(255),
primary key(ID)
);

INSERT INTO TB_COLABS (NOME, SALARIO, FUNCAO, SETOR, SUPERIOR)
VALUE ("Lucas",1346.32,"Auxiliar","Almoxarifado","Alice");
INSERT INTO TB_COLABS (NOME, SALARIO, FUNCAO, SETOR, SUPERIOR)
VALUE ("Helena",2983.12,"Supervisora","Financeiro","João");
INSERT INTO TB_COLABS (NOME, SALARIO, FUNCAO, SETOR, SUPERIOR)
VALUE ("Michele",1826.32,"Assistente","Secretária","Bernadete");
INSERT INTO TB_COLABS (NOME, SALARIO, FUNCAO, SETOR, SUPERIOR)
VALUE ("João",3346.32,"Gerente","Financeiro","Jorge");
INSERT INTO TB_COLABS (NOME, SALARIO, FUNCAO, SETOR, SUPERIOR)
VALUE ("Alice",1346.32,"Supervisora","Almoxarifado","André");

SELECT * FROM TB_COLABS WHERE SALARIO > 2000;

SELECT * FROM TB_COLABS WHERE SALARIO < 2000;

SET SQL_SAFE_UPDATES = 0;

UPDATE TB_COLABS SET FUNCAO = "Estagiário" WHERE ID = 1;

SELECT * FROM TB_COLABS;